using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Cptis.Core
{
    public class CaseProgress
    {
        /// <summary>
        /// The system assigned unique identifier for the case progress note
        /// </summary>
        public int CaseProgressId { get; set; }
        /// <summary>
        /// Number assigned to the case progress note, displayed for the user to see.  Unique to the case only, not the entire system
        /// </summary>
        public string CaseProgressNum { get; set; }
        /// <summary>
        /// This is the case number generated by DCF
        /// </summary>
        public string CaseNumber { get; set; }
        /// <summary>
        /// Audit details about when the client was created and modified
        /// </summary>
        public Audit Audit { get; set; } = new();
        /// <summary>
        /// FK to the client demographic record of the person the case note is about
        /// </summary>
        public int ClientDemographicId { get; set; }
        /// <summary>
        /// FK to the registration record
        /// </summary>
        public int RegistrationId { get; set; }
        /// <summary>
        /// The date of the activity the case note is referencing
        /// </summary>
        public DateTime ActivityDate { get; set; }
        /// <summary>
        /// The clock time of the activity that the case note is referencing
        /// </summary>
        public string ActivityTime { get; set; }
        /// <summary>
        /// The activity that the case note is referencing
        /// </summary>
        public string Activity { get; set; }
        /// <summary>
        /// FK to the provider record a provider
        /// </summary>
        public string ProviderId { get; set; }
        /// <summary>
        /// The date the case note was entered.
        /// </summary>
        public DateTime EntryDate { get; set; }
        /// <summary>
        /// Large block of text for case activity description
        /// </summary>
        public string CaseActivityComment { get; set; }
        /// <summary>
        /// Date database record created
        /// </summary>
        public DateTime CreateDate { get; set; }
        /// <summary>
        /// Date Database record updated
        /// </summary>
        public DateTime UpdateDate { get; set; }
        /// <summary>
        /// User First Name who updated case note record
        /// </summary>
        public string UserFirstName { get; set; }
        /// <summary>
        /// User last name of person who updated case note record
        /// </summary>
        public string UserLastName { get; set; }
        /// <summary>
        /// Is case note linked
        /// </summary>
        public string IsLinked { get; set; }
        /// <summary>
        /// Signature/attestation of case note preparer. 
        /// </summary>
        public string PreparedBy { get; set; }
        /// <summary>
        /// Date of case note signature
        /// </summary>
        public DateTime PreparedDate { get; set; }
        /// <summary>
        /// Person who reviewed the activity and case note
        /// </summary>
        public string ReviewedBy { get; set; }
        /// <summary>
        /// Date the person who reviewed the activity and case note did the action
        /// </summary>
        public DateTime ReviewedDate { get; set; }
        /// <summary>
        /// Designation of the CPT Office where the note occurrred.
        /// </summary>
        public string CptOffice { get; set; }
        /// <summary>
        /// is case note autogenerated
        /// </summary>
        public bool Autogenerated { get; set; }
        /// <summary>
        /// is case note deleted
        /// </summary>
        public bool IsDeleted { get; set; }

        /// <summary>
        /// Registration linked to case note
        /// </summary>
        public Registration Registration { get; set; }
        /// <summary>
        /// Client that the case note is about
        /// </summary>
        public ClientDemographic ClientDemographic { get; set; }
        /// <summary>
        /// Provider who performed actions described in case note
        /// </summary>
        public Provider Provider { get; set; }
        /// <summary>
        /// linked registrations to case note
        /// </summary>
        public ICollection<CaseProgressLinkedReg> LinkedRegistrations { get; set; } = [];
    }
}
